version: '3.4'

services:
  cortex-diary-nucleus.in.api:
    env_file:
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 192.168.8.131:60020:80
  cortex-diary-nucleus.out.api:
    env_file: 
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 192.168.8.131:60021:80