version: '3.4'

services:
  in.api:
    env_file:
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - C:\db:C:\db
    ports:
      - "60020:80"
  out.api:
    env_file: 
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - C:\db:C:\db
    ports:
      - "60021:80"
networks:
  default:
    external:
      name: nat